SecondBackEnd/Controllers/CategoryController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using SecondBackEnd.Data;
using SecondBackEnd.Models;

namespace SecondBackEnd.Controllers
{
    [Authorize]
    public class CategoryController : Controller
    {
        private readonly ApplicationDbContext _db;
        public CategoryController(ApplicationDbContext db)
        {
            _db = db;
        }
        public IActionResult Index()
        {
            IEnumerable<Category> objCategoryList= _db.Categories;
            return View(objCategoryList);
        }
    }
}

SecondBackEnd/Controllers/RegisterAccountController.cs
using Microsoft.AspNetCore.Mvc;
using SecondBackEnd.Data;
using SecondBackEnd.Models;

namespace SecondBackEnd.Controllers
{
    public class RegisterAccountController : Controller
    {
        private readonly ApplicationDbContext _db;
        public RegisterAccountController(ApplicationDbContext db)
        {
            _db = db;
        }

        //GET
        public IActionResult Register()
        {
            return View();
        }

        //POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Register(Test obj)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    _db.Tests.Add(obj);
                    _db.SaveChanges();
                    TempData["success"] = "User information is created successfully";
                    return RedirectToAction("Index", "TestHome");
                }
                catch (Exception ex)
                {
                   ModelState.AddModelError("Email", "An user has already use this Email Address");
                }
            }
            return View(obj);
        }

        public IActionResult Edit(int? id)
        {
            if (id == null || id == 0) { 
                return NotFound();
            
            }
            var recordFromDB = _db.Tests.Find(id);
            if (recordFromDB == null)
            {
                return NotFound();
            }
            return View(recordFromDB);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Test obj)
        {
            if (ModelState.IsValid)
            {
                _db.Tests.Update(obj);
                _db.SaveChanges();
                TempData["success"] = "User information is edited successfully";
                return RedirectToAction("Index", "TestHome");
            }
            return View(obj);
        }

        public IActionResult Delete(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();

            }
            var recordFromDB = _db.Tests.Find(id);
            if (recordFromDB == null)
            {
                return NotFound();
            }
            return View(recordFromDB);
        }

        //POST
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeletePost(int? id) {
            var obj = _db.Tests.Find(id);
            if (obj == null)
            {
                return NotFound();
            }
            _db.Tests.Remove(obj);
            _db.SaveChanges();
            TempData["success"] = "User information is deleted successfully";
            return RedirectToAction("Index", "TestHome");
        }
    }
}

SecondBackEnd/Controllers/TestHomeController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using SecondBackEnd.Data;
using SecondBackEnd.Models;

namespace SecondBackEnd.Controllers
{
    [Authorize]
    public class TestHomeController : Controller
    {
        private readonly ApplicationDbContext _db;
        public TestHomeController(ApplicationDbContext db)
        {
            _db = db;
        }
        public IActionResult Index()
        {
            IEnumerable<Test> objTestList = _db.Tests;
            return View(objTestList);
        }
    }
}

SecondBackEnd/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SecondBackEnd</title>
    <link rel="stylesheet" href="~/css/bootswatchTheme.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/SecondBackEnd.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Views/Shared/style.css" asp-append-version="true" />
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.4/font/bootstrap-icons.css">
    <script src="~/script.js"></script>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">SecondBackEnd</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor03" aria-controls="navbarColor03" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarColor03">
      <ul class="navbar-nav me-auto">
        <li class="nav-item">
          <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link text-dark" asp-area="" asp-controller="Category" asp-action="Index">Category</a>
        </li>
        <li class="nav-item">
          <a class="nav-link text-dark" asp-area="" asp-controller="TestHome" asp-action="Index">Test</a>
        </li>
        <li class="nav-item">
          <a class="nav-link text-dark" asp-area="" asp-controller="RegisterAccount" asp-action="Register">Register Account</a>
        </li>
        <li class="nav-item">
          <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Logout">LogOut</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Dropdown</a>
          <div class="dropdown-menu">
            <a class="dropdown-item" href="#">Action</a>
            <a class="dropdown-item" href="#">Another action</a>
            <a class="dropdown-item" href="#">Something else here</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="#">Separated link</a>
          </div>
        </li>
      </ul>
      <form class="d-flex">
        <input class="form-control me-sm-2" type="search" placeholder="Search">
        <button class="btn btn-secondary my-2 my-sm-0" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            <partial name="_Notification" />
            @RenderBody()
        </main>
    </div>

    <footer class="footer text-muted bg-dark">
        <div class="container">
            &copy; 2023 - SecondBackEnd - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

SecondBackEnd/Views/Shared/_Notification.cshtml
@if(TempData["success"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.success('@TempData["success"]');
	</script>
}
@if(TempData["error"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.error('@TempData["error"]');
	</script>
}